<?php

/**
 * @file
 * The Facet API Date Popup Calendar module.
 */


/**
 * Implements hook_facetapi_facet_info_alter().
 */
function facetapi_date_popup_calendar_facetapi_facet_info_alter(array &$facet_info, array $searcher_info) {
  switch ($searcher_info['adapter']) {
    case 'search_api':
      _facetapi_date_popup_calendar_associate_widget($facet_info);
      break;
  }
}

/**
 * Associates all date fields with the "date_per_day" query type.
 *
 * @param array &$facet_info
 *   The facet definitions passed to hook_facetapi_facet_info_alter().
 */
function _facetapi_date_popup_calendar_associate_widget(array &$facet_info) {
//mail('koen@seemeonline.nl', 'facet_info', print_r($facet_info, true));
  foreach ($facet_info as $name => $info) {
    $query_types = array_flip($info['query types']);
    // The check on "field type" is specific to Search Api.
    $field_type = empty($info['field type']) ? '' : $info['field type'];

    // @todo check if there is a beter way to do this.
    if (isset($query_types['date']) || 'list<date>' == $field_type) {
      // This widget needs a different way to set labels
      // so we add our own callback.
      $facet_info[$name]['map options']['value callback'] = '_date_per_day_query_api_facet_create_label';
      $facet_info[$name]['query types'][] = 'date_per_day';
    }
  }
}

/**
 * Value callback for labels with the date per day type.
 */
function _date_per_day_query_api_facet_create_label(array $values, array $options) {
  $map = array();
  // Loop through all the values to create a map.
  // It does nothing yet but more functionality might be added.
  foreach ($values as $key => $value) {
  $value = substr($value, 0, -10);
    $map[$key] = $value;
  }
//  mail('koen@seemeonline.nl', 'map', print_r($map, true));
  return $map;
}
